### ISSUE TITLE
presentation layer (Layer 3 retrofit): hundred-square grid-table content format (taxonomy pattern 7)

### ISSUE THREAD

**Issue by ontheroadjp** [ontheroadjp/100-square-calculations#270]
## Overview
Retrofit the "grid table" content format (taxonomy pattern 7: `build_hundred_square_block_tex`, the `100` command's addition table) to guidelines-doc-compliant shared TeX components. #229 ports the existing grid visuals as-is onto the internal presentation API; this issue is the guidelines-doc-compliant macro retrofit that #229 explicitly defers. Child of #185 (#166 B-6).

## Background
`docs/latex/tex_content_format_taxonomy.md` maps `build_hundred_square_block_tex` (`100`) to pattern 7: an `HUNDRED_SQUARE_SIZE` x `HUNDRED_SQUARE_SIZE` `tabular` returned as one whole block, with no per-problem number concept and `\rowcolor`/`\columncolor` header coloring — unlike every other pattern. #229's Done Criteria preserves current visuals as-is and states "guidelines-doc-compliant macro retrofit is #185's scope, not this one's". This issue does that retrofit. Depends on #229 (the `100` internal-API migration must be live first).

Common constraints (shared across the #185 retrofit children):
- Not in scope: Layer 1 (page shell) / Layer 2 (content-area base layout, problem-number box / #184) changes; changing the internal presentation API surface (`build_presentation_document_tex` contract, #183); `docs/L0_concept/` changes; other taxonomy patterns.
- References: `docs/latex/tex_content_format_taxonomy.md`; `docs/latex/tex_calculation_drill_layout_guidelines.md` (shared macros, centralized layout lengths; per-problem defect items 6, 12, 13, 20).

## Scope (initial estimate)
- Add a shared TeX component for the hundred-square grid: centralized layout values for cell size, header row/column coloring, rule widths and table metrics (items 6, 12, 20), instead of inline `tabular` construction in the `build_*` function
- Port `build_hundred_square_block_tex` (and the `100` slot-content path introduced by #229) to emit via it
- Fix grid-level layout defects surfaced during retrofit: cell width uniformity across 1-2 digit entries, header emphasis consistency, outer/inner rule weights, optional tabular-figure use for the numerals (item 13)
- Not in scope: common exclusions above; changing the table's mathematical content or size; other patterns

## Done Criteria
- `build_hundred_square_block_tex` / the `100` slot-content path emits via the shared, guidelines-doc-compliant grid component (no inline ad hoc `tabular` metrics)
- Known grid-level layout defects at issue start are resolved or explicitly triaged
- `100` PDFs still render valid output via the internal presentation API; visual-only changes covered by new or updated automated tests

**Comment by ontheroadjp** [comment]
Implemented on `feat/270-hundred-square-grid-component` (commit a43a730).

**Source (`backend/nuts_calc_tex.py`)**
- Added 3 module constants after the #268 pattern-5 constants: `CONTENT_FORMAT_HUNDRED_SQUARE_CELL_WIDTH_TEX = '1.6em'`, `CONTENT_FORMAT_HUNDRED_SQUARE_COLSEP_TEX = '6pt'`, `CONTENT_FORMAT_HUNDRED_SQUARE_RULE_WIDTH_TEX = '0.4pt'` (the last two = LaTeX defaults, so centralization only).
- `build_content_format_macros_tex()`: ADD-only, appended strictly after the `\stagedchaineq` line (#264–#268 definitions untouched): `\newlength`+`\setlength` for `\hundredsquarecellwidth` / `\hundredsquarecolsep` / `\hundredsquarerulewidth`, `\newcommand{\hundredsquareheadercolor}{lightgray}` (from `HUNDRED_SQUARE_HEADER_COLOR`), and `\newcommand{\hundredsquarecell}[1]{\hbox to \hundredsquarecellwidth{\hfil #1\hfil}}`. Docstring bullet added.
- New `build_hundred_square_grid_tex(table, show_answer)`: emits the whole `\begin{center}…\end{center}` block via the shared components — every header/data entry wrapped in `\hundredsquarecell`, `\tabcolsep`/`\arrayrulewidth` set from the centralized lengths inside the `center` group, header shading via `\columncolor{\hundredsquareheadercolor}` / `\rowcolor{\hundredsquareheadercolor}` (no inline literal color). `\hbox to` (not `\makebox[`) preserves #229's number-box-absence assertions.
- `build_hundred_square_block_tex` → thin delegate to `build_hundred_square_grid_tex`. `build_hundred_square_slot_content_tex` unchanged (still delegates to the block builder), so the CLI/subprocess and internal-presentation-API paths stay byte-identical. No change to the table's math content or `HUNDRED_SQUARE_SIZE`.

**Grid-level defects**
- Resolved: ragged per-column widths across 1–2-digit entries (fixed-width centered cells, guidelines items 6/11/20); header-color, `\tabcolsep`, `\arrayrulewidth` now each have a single tuning point (items 6/12).
- Triaged (same as #264–#268): tabular figures / dedicated digit font (items 13/14). 3–4-digit operand ranges (`--a-digits 3`) may slightly overfill the fixed cell — same accepted tradeoff as the pattern-5 memo box; issue scope names 1–2-digit entries as the design target.

**Tests**
- New `backend/tests/test_nuts_calc_tex_hundred_square_content_format.py` (13 tests): macro-block contents + constants, #264–#268 defs intact, macro splice into both `build_document_tex` and `build_presentation_document_tex`, `build_hundred_square_grid_tex` blank/filled body (all entries wrapped, no literal color, no `\makebox[`, `\hline`/row-terminator counts), block==grid==slot delegation, and real-PDF compiles for blank+filled × pdflatex+lualatex plus the presentation-API path × both engines. No skips (both engines present).
- Updated header-color assertions in `test_nuts_calc_tex_hundred_square_generation.py` and `test_web_backend_app.py` to the `\hundredsquareheadercolor` form.

**Validation**
- `cd backend && python3 -m pytest -q`: **1029 passed**, 0 failed (exit 0, 4m09s).
- Targeted set (`hundred_square_generation`, `presentation_api`, `content_area_layout`, `web_backend_app`): 181 passed.

Docs (taxonomy pattern-7 retrofit-status bullet, guidelines pattern-7 section + "未適用" line, `specification_summary.md` #185 history) to be synced via /docs-sync in the PR. L3 per-file doc `docs/L3_implementation/backend/nuts_calc_tex.py.md` updated in this commit.

**Comment by ontheroadjp** [comment]
Delivered via PR #280, squash-merged to `main` as `9b643c3` (`feat(#270): render the hundred-square grid table via shared TeX components (#280)`).

pattern-7 (`build_hundred_square_block_tex`, the `100` addition table) now emits via the shared, guidelines-doc-compliant `build_hundred_square_grid_tex` helper + `\hundredsquarecell` / `\hundredsquarecolsep` / `\hundredsquarerulewidth` / `\hundredsquareheadercolor` macros in `build_content_format_macros_tex()`; `build_hundred_square_slot_content_tex` and the table's math content/size unchanged. Full backend suite 1048 passed / 0 failed at the merged head.

Note: this issue was not auto-closed on merge because PR #280's description had been overwritten (shared session-temp-dir collision with the parallel #269 worker) with a "Closes #269" line; the PR body has been corrected post-merge. The code, squash commit message, and docs on `main` are all correct for #270.
